### ISSUE TITLE
Some SA1 games not working when using stdbool

### ISSUE THREAD

**Issue by netux79** [libretro/CATSFC-libretro#10]
Starting with this commit 4a54fd4018adf931fb436acba2399efc6d6d1176, some games with SA1 (like Mario RPG) are not working correctly (black screen when SA1 active). It seems that using stdbool brought a bug with it.

**Comment by aliaspider** [comment]
nice catch! and here I thought that catsfc simply didn't support Mario RPG.
fixed in 735bc9b39a4eb1de6aef4c4b1af6e0b48d578bde.

**Comment by netux79** [comment]
You are fast aliaspider... thank you!
