### ISSUE TITLE
remove "CFLAGS :=" to allow use of env CFLAGS

### ISSUE THREAD

**Issue by joolswills** [libretro/CATSFC-libretro#4]
on retropie (for example) we use CFLAGS/CXXFLAGS to set arm cpu etc. 

https://github.com/libretro/CATSFC-libretro/blob/master/Makefile#L39 overrides the environment variable so it would be useful for us for this to be removed.

**Comment by aliaspider** [comment]
fixed 361b6927ef6af4e0913f18909cb841fd192e69d1.

pull requests are also accepted around here, and are also more suited for this kind of requests.

you can also just edit the file directly in the browser and github will automatically fork the repo to your account and offer you the option to do a pull request.

**Comment by joolswills** [comment]
thanks - I was short on time, and since it was a one-liner, I thought it would be easier just to mention it first.

**Comment by joolswills** [comment]
hadn't realised i could edit the file via github interface - nice feature :) cheers.
